services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    image: ecor:latest
    command: >
      /bin/sh -c 'python sender.py'
    env_file: ".env"

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    image: ecor:latest
    command: >
      /bin/sh -c 'python receiver.py'
    env_file: ".env"
